// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7xnbnU4yhVR5X5Prj4NOW-0nfQWDzZo',
    appId: '1:360624119727:web:df7b72ec5935c68d01995a',
    messagingSenderId: '360624119727',
    projectId: 'ieltim',
    authDomain: 'ieltim.firebaseapp.com',
    storageBucket: 'ieltim.firebasestorage.app',
    measurementId: 'G-F6MFCDWT9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhQTXJ5UMBVjjdFiE1JPVlZ_4yPfO5wEQ',
    appId: '1:360624119727:android:99b30b67cc5bf30c01995a',
    messagingSenderId: '360624119727',
    projectId: 'ieltim',
    storageBucket: 'ieltim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BOLRSsEmAYg6jCYpwEdyKcng7IsVtI4',
    appId: '1:360624119727:ios:ab953a91f234fb4501995a',
    messagingSenderId: '360624119727',
    projectId: 'ieltim',
    storageBucket: 'ieltim.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
